services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: discord-bot
    restart: unless-stopped

    env_file:
      - stack.env

    volumes:
      - discord_bot_data:/data

volumes:
  discord_bot_data:
    external: true
    name: kardio-bot_discord_bot_data
